# -*- coding: utf-8 -*-
"""numpy_task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I-txY_wtFBreQp5ZNPE6hJd-SxzFLP65
"""

!pip install numpy
import numpy as np
print(np.__version__)

import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(a+b)

a = np.zeros((5,3))
a

a = np.ones((5,3))
a

a = np.full((4,7),18)
a

a = np.empty((5,5))
a

a = np.eye(5)
a

a = np.arange(5,50)
a

a = np.arange(2,20,2)
a

a = np.arange(0,20,3)
a

a = np.linspace(1,10,3)
a

a = np.random.randn(10)
a

a = np.random.randint(10)
a

colours = ["red","Green","Pink","Orange","Blue","white","Black"]
n = int(input("Enter the colour number (limit 7): "))
print(np.random.choice(colours,n))

#copy
a = np.array([1,2,3])
new = a.copy()
new[1] = 200
print("Array values : ",a)
print("Copy values : ",new)

# view
a = np.array([1,2,3])

new = a.view()
new[1] = 200
print("Array values : ",a)
print("Copy values : ",new)

#borad casting (updating)
a = np.array([5,10,15,20,25,30])
a += 10
print("Updated values : ",a)

a=np.array([1,2,3,4,5])
b=np.array([5,6,7,8,9])

print(np.add(a,b))

a=np.array([1,2,3,4,5])
b=np.array([5,6,7,8,9])

print(np.multiply(a,b))
print(np.subtract(a,b))
print(np.divide(a,b))

a=np.array([100,90,80,70,60])
b=np.array([50,40,30,20,10])

print(np.subtract(a,b))

a=np.array([125,60,50,75,36])
b=np.array([5,6,5,5,6])

print(np.divide(a,b))

a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])

print(np.dot(a,b))

a = np.array([1,2,3,4,5,6,7,8,9])
print(np.sum(a))

a = np.array([1,2,3,4,5,6,7,8,9])
print(np.mean(a))

a = np.array([1,2,3,4,5,6,7,8,9])
print(np.max(a))

a = np.array([1,2,3,4,5,6,7,8,9])
print(np.min(a))

a = np.array([1,2,3,4,5,6,7,8,9])
print(np.std(a))

a = np.array([4,9,16,25,36,49])
print(np.sqrt(a))

a = np.array([9,4,7,3,8,9,4,1,11,141,34])
print(np.sort(a))

a = np.array([9,4,7,3,8,9,4,1,11,141,34])
print(np.unique(a))

a = np.array([[9,4,7,3,4],
              [1,5,14,5,2]])
print(a.shape)

a = np.array([9,4,7,3,8,9,4,1,11,141,34])
print(np.size(a))

a = np.array([9,4,7,3,8,9,4,1,11,141,34])
print(a.itemsize)

a = np.array([[9,4,7,3,4],
              [1,5,14,5,2]])
print(a.ndim)

a = np.array([[9,4,7,3,4],
              [1,5,14,5,2]])
print(a.dtype)

a = np.array([[9,4,7,3,4],
              [1,5,14,5,2]])
print(a[0,1])
print(a[1,1])
print(a[:,3])
print(a[1,:])

a = np.array([9,4,7,3,8,9,4,1,11,141,34,55,24,9,23])
print("Original Array ",a)

new = a.reshape(5,3)
print("\nReshaped Array \n",new)

